# Generated by Django 4.1.13 on 2024-05-27 17:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupEmail',
            fields=[
                ('backup_email_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permission_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubication',
            fields=[
                ('ubication_id', models.AutoField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('department', models.CharField(max_length=100, verbose_name='Department')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('neighborthood', models.CharField(max_length=100, verbose_name='Neighborthood')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Postal code')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Location')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('permission', models.ManyToManyField(related_name='permissions', to='authApp.permission')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], max_length=20, verbose_name='Type')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('document', models.CharField(max_length=15, verbose_name='Document')),
                ('nit', models.CharField(max_length=18, verbose_name='NIT')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('backupEmail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authApp.backupemail')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authApp.phone')),
                ('role', models.ManyToManyField(related_name='user', to='authApp.role')),
                ('ubication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='authApp.ubication')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
        ),
    ]
