# Generated by Django 4.1.13 on 2024-05-27 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_alter_user_backupemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authApp.phone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ubication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authApp.ubication'),
        ),
    ]
