# Generated by Django 4.1.13 on 2024-05-17 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userRole_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('user', models.IntegerField(verbose_name='User')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRole', to='authApp.role')),
            ],
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('rolePermission_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned at')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolePermission', to='authApp.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolePermission', to='authApp.role')),
            ],
        ),
    ]
