# Generated by Django 4.1.13 on 2024-05-21 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_permission_description_alter_role_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], max_length=20, verbose_name='Type')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company name')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('document', models.CharField(max_length=15, verbose_name='Document')),
                ('nit', models.CharField(max_length=18, verbose_name='NIT')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('status', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UserRole', to='authApp.user'),
        ),
    ]
