# Generated by Django 4.1.13 on 2024-06-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_user_phone_alter_user_ubication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('authApp.show_warehouses', 'Can view warehouses')]},
        ),
    ]
