# Generated by Django 4.1.13 on 2024-06-02 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('authApp.show_warehouses', 'Can view warehouses'), ('authApp.create_warehouses', 'Can create warehouses'), ('authApp.update_warehouses', 'Can update warehouses'), ('authApp.partial_update_warehouses', 'Can update partially warehouses'), ('authApp.delete_warehouses', 'Can delete warehouses'), ('authApp.show_warehouse_buildings', 'Can view buildings filtered by warehouses'), ('authApp.show_locations', 'Can view locations'), ('authApp.create_locations', 'Can create locations'), ('authApp.update_locations', 'Can update locations'), ('authApp.partial_update_locations', 'Can update partially locations'), ('authApp.delete_locations', 'Can delete locations'), ('authApp.show_buildings', 'Can view buildings'), ('authApp.create_buildings', 'Can create buildings'), ('authApp.update_buildings', 'Can update buildings')]},
        ),
    ]
