# Generated by Django 4.1.13 on 2024-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authApp', '0008_alter_user_options_user_product_ids_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nit',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('Jurídica', 'Jurídica'), ('Natural', 'Natural')], max_length=20, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='users', to='auth.group'),
        ),
    ]
